-- Ejecutá este script una sola vez en Supabase: SQL Editor > New query > Run.
create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  codigo text not null,
  descripcion text not null,
  marca text not null,
  talle text,
  color text,
  ubicacion text not null,
  stock_teorico numeric not null default 0,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists productos_codigo_unico on public.productos (lower(codigo));

create table if not exists public.movimientos (
  id bigint generated by default as identity primary key,
  codigo text not null,
  descripcion text,
  cantidad numeric not null,
  usuario text,
  fecha text,
  hora text,
  tipo text not null default 'conteo',
  deposito text not null default 'Ático',
  created_at timestamptz not null default now()
);

create table if not exists public.depositos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists depositos_nombre_unico on public.depositos (lower(nombre));
insert into public.depositos (nombre, activo) values ('Ático', true) on conflict do nothing;
