-- Ejecutar una sola vez en Supabase > SQL Editor antes de usar depósitos y salidas.
create table if not exists public.depositos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists depositos_nombre_unico on public.depositos (lower(nombre));
insert into public.depositos (nombre, activo) values ('Ático', true) on conflict do nothing;

alter table public.movimientos add column if not exists deposito text;
update public.movimientos set deposito = 'Ático' where deposito is null or btrim(deposito) = '';
alter table public.movimientos alter column deposito set default 'Ático';

-- Permite el nuevo perfil de operador que solo registra salidas.
alter table public.usuarios drop constraint if exists usuarios_rol_check;
alter table public.usuarios add constraint usuarios_rol_check check (rol in ('admin', 'operador', 'salida'));
