-- Ejecutar una sola vez en Supabase > SQL Editor. No modifica productos ni movimientos.
create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  password_hash text not null,
  rol text not null check (rol in ('admin', 'operador')) default 'operador',
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists usuarios_nombre_unico on public.usuarios (lower(nombre));
